[package]
name = "multithreading_task"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
